var fruit=[
			{
				id:1,
				name:'菠萝',
				dj:3,
				num:1,
				src:"images/bl.jpg",
			},
			{
				id:2,
				name:'草莓',
				dj:12,
				num:1,
				src:"images/cm.jpg",
			},
			{
				id:3,
				name:'哈密瓜',
				dj:5,
				num:1,
				src:"images/hmg.jpg",
			},
			{
				id:4,
				name:'橘子',
				dj:2,
				num:1,
				src:"images/jz.jpg",
			}
		];
var app=angular.module('app',[]);
app.controller('c1',function($scope){
	$scope.arr=fruit;
	$scope.newarr=[];
	$scope.sum=0;
	$scope.m123;
	$scope.gmfn=function(v){
		var flag=true;
		angular.forEach($scope.newarr,function(data,index,arr){
			if(v.id==data.id){
					flag=false;
					data.num++;
					data.sum=v.dj*data.num;
			}
		})
		if(flag){
			$scope.newarr.push({
				id:v.id,
				name:v.name,
				dj:v.dj,
				num:v.num,
				sum:v.dj,
				src:v.src
			});
		}
	}
	$scope.dd1=function(v,k){
		--v.num;
		v.sum=v.num*v.dj;
		if(v.num<=0){
			$scope.dd2(k);
		}
		console.dir($scope.newarr);
	}
	$scope.dd2=function(k){
		$scope.newarr.splice(k,1);
	}
	$scope.dd3=function(v){
		v.num++;
		v.sum=v.num*v.dj;
	}
	$scope.dd4=function(){
		$scope.sum=0;
		angular.forEach($scope.newarr,function(data,index,arr){
			$scope.sum+=data.dj*data.num;
		});
	}
	$scope.$watch(function(){
		return $scope.newarr;
	},function(newVal,oldVal,scope){
		$scope.dd4();
	},true);
});